<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.hawkins</groupId><artifactId>gallery-parent</artifactId><version>1.0.0-SNAPSHOT</version></parent><artifactId>gallery-core</artifactId><dependencies>
<dependency><groupId>com.hawkins</groupId><artifactId>gallery-persistence</artifactId></dependency>
<dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter</artifactId></dependency>
<dependency><groupId>org.springframework</groupId><artifactId>spring-tx</artifactId></dependency>
<dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
<dependency><groupId>net.coobird</groupId><artifactId>thumbnailator</artifactId><version>${thumbnailator.version}</version></dependency>
<dependency><groupId>com.drewnoakes</groupId><artifactId>metadata-extractor</artifactId><version>${metadata-extractor.version}</version></dependency>
<dependency><groupId>com.twelvemonkeys.imageio</groupId><artifactId>imageio-webp</artifactId><version>${twelvemonkeys.version}</version></dependency>
<dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><optional>true</optional></dependency>
<dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
</dependencies></project>
